### ISSUE TITLE
Training with custom datasets

### ISSUE THREAD

**Issue by tedyhabtegebrial** [xuchen-ethz/continuous_view_synthesis#1]
Hi,

I see that you are dividing the translation vector by 50( see link below).  Do I have to modify my translation vectors? Could you please explain the way to represent the camera poses for street scene datasets?

https://github.com/xuchen-ethz/continuous_view_synthesis/blob/c6fc39e5ef4a21b8b33154404c71c4d53625fe8c/data/kitti_data_loader.py#L54

**Comment by mbanani** [comment]
@tedyhabtegebrial Did you find why the translation was scaled by a factor of 50? Thank you!

**Comment by tedyhabtegebrial** [comment]
Looking at their code, I can see that dividing by 50 is needed for this dataset only. Since they use a smaller subset of KITTI provided by another paper; my guess is that the division was necessary based on how the other authors per-processed the dataset.
